default_language_version:
  python: python3
repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]
        exclude: migrations/
        files: .py$
  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
        exclude: migrations/
        args: ["--line-length", "120"]
        files: .py$
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        exclude: migrations/
        args: ["--max-line-length", "120"]
        files: .py$
ci:
  autofix_prs: false
