# Generated by Django 4.0.3 on 2022-03-13 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='BaseModel.created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='BaseModel.updated_at')),
                ('name', models.TextField(verbose_name='Goods.name')),
                ('description', models.TextField(blank=True, verbose_name='Goods.description')),
                ('link', models.TextField(blank=True, verbose_name='Goods.link')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='BaseModel.created_by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='BaseModel.created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='BaseModel.updated_at')),
                ('name', models.TextField(verbose_name='Organization.name')),
                ('description', models.TextField(verbose_name='Organization.description')),
                ('contact', models.TextField(verbose_name='Organization.contact')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='BaseModel.created_by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Poi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='BaseModel.created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='BaseModel.updated_at')),
                ('name', models.TextField(verbose_name='Poi.name')),
                ('description', models.TextField(verbose_name='Poi.description')),
                ('contact', models.TextField(verbose_name='Poi.contact')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='BaseModel.created_by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization', verbose_name='Poi.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Needs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='BaseModel.created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='BaseModel.updated_at')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Needs.quantity')),
                ('unit', models.CharField(choices=[('Needs.Units.kg', 'Kg'), ('Needs.Units.l', 'L'), ('Needs.Units.pcs', 'Pcs')], max_length=16, verbose_name='Needs.unit')),
                ('due_time', models.DateTimeField(verbose_name='Needs.due_time')),
                ('status', models.CharField(choices=[('Needs.Status.active', 'Active'), ('Needs.Status.disabled', 'Disabled')], max_length=32, verbose_name='Needs.status')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='BaseModel.created_by')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.goods', verbose_name='Needs.good')),
                ('poi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.poi', verbose_name='Needs.poi')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
