# Generated by Django 4.0.3 on 2022-03-14 20:40

from django.db import migrations


def apply_migration(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    Group = apps.get_model("auth", "Group")
    Group.objects.using(db_alias).bulk_create(
        [
            Group(name="Regular user"),
            Group(name="Org admin"),
            Group(name="POI admin"),
            Group(name="POI user"),
        ]
    )


def revert_migration(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name__in=["Regular user", "Org admin", "POI admin", "POI user"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(apply_migration, revert_migration)
    ]
