# Generated by Django 4.0.3 on 2022-03-16 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_auto_20220314_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoiMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='BaseModel.created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='BaseModel.updated_at')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='poi',
            name='members',
            field=models.ManyToManyField(related_name='members', through='core.PoiMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poimembership',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='BaseModel.created_by'),
        ),
        migrations.AddField(
            model_name='poimembership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group'),
        ),
        migrations.AddField(
            model_name='poimembership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poimembership',
            name='poi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.poi'),
        ),
    ]
