# Generated by Django 4.0.3 on 2022-03-16 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_poimembership_alter_user_managers_poi_members_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poi',
            name='organization',
        ),
    ]
