# Generated by Django 4.0.3 on 2022-03-16 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_poi_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='poi',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='core.poi'),
            preserve_default=False,
        ),
    ]
