# Generated by Django 4.0.3 on 2022-03-18 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220317_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needs',
            name='status',
            field=models.CharField(choices=[('Needs.Status.active', 'Active'), ('Needs.Status.disabled', 'Disabled'), ('Needs.Status.fulfilled', 'Fulfilled')], max_length=32, verbose_name='Needs.status'),
        ),
        migrations.AlterField(
            model_name='needs',
            name='unit',
            field=models.CharField(choices=[('Needs.Units.kg', 'Kg'), ('Needs.Units.l', 'L'), ('Needs.Units.pcs', 'Pcs')], max_length=16, verbose_name='Needs.unit'),
        ),
        migrations.CreateModel(
            name='Shipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='BaseModel.created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='BaseModel.updated_at')),
                ('status', models.CharField(choices=[('Shipments.Status.to_do', 'To Do'), ('Shipments.Status.in_progress', 'In Progress'), ('Shipments.Status.done', 'Done')], max_length=32, verbose_name='Shipments.status')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='BaseModel.created_by')),
                ('need', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.needs', verbose_name='Shipments.need')),
            ],
            options={
                'verbose_name': 'Shipments',
                'verbose_name_plural': 'Shipments',
            },
        ),
    ]
