# Generated by Django 4.0.3 on 2022-03-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_needs_status_alter_needs_unit_shipments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needs',
            name='status',
            field=models.CharField(choices=[('active', 'Needs.Status.active'), ('disabled', 'Needs.Status.disabled'), ('fulfilled', 'Needs.Status.fulfilled')], default='active', max_length=32, verbose_name='Needs.status'),
        ),
        migrations.AlterField(
            model_name='needs',
            name='unit',
            field=models.CharField(choices=[('kg', 'Needs.Units.kg'), ('l', 'Needs.Units.l'), ('pcs', 'Needs.Units.pcs')], max_length=16, verbose_name='Needs.unit'),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='status',
            field=models.CharField(choices=[('in progress', 'Shipments.Status.in_progress'), ('done', 'Shipments.Status.done')], max_length=32, verbose_name='Shipments.status'),
        ),
    ]
